// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // The CLI (migrate, db pull, studio) needs a DIRECT connection — Neon's
  // pooled endpoint (PgBouncer) can't run migrations. Runtime queries use the
  // pooled DATABASE_URL via the @prisma/adapter-neon driver adapter in lib/db.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
